ref #275: Add WIP for hreflang header output
chameleon-system/chameleon-shop-theme-bundle pull request #21
Opened 2019-01-25 08:59 UTC by UlrichKu

| Q             | A
| ------------- | ---
| Branch        | 6.2.x
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed issues  | https://github.com/chameleon-system/chameleon-system/issues/275
| License       | MIT

2019-02-15 09:01 UTC, umulmrum requested changes

2019-02-15 09:01 UTC, umulmrum commented on Resources/views/webModules/MTPageMeta/standard.view.php
> +// TODO what about other MTPageMeta/standard.view.php ("non-theme")?
We should add an update script in chameleon-base that tells the user what to do.

2019-02-15 09:01 UTC, umulmrum commented on Resources/views/webModules/MTPageMeta/standard.view.php
> +if (\count($data['language-alternatives']) > 0) {
We can omit this `if` - if the array is empty, the loop won't do work anyway.

2019-02-15 12:59 UTC, UlrichKu commented on Resources/views/webModules/MTPageMeta/standard.view.php
> +if (\count($data['language-alternatives']) > 0) {
ok

My thinking was that it is not guaranteed that this array is present at all.
But it will be (if the core PR is merged).

2019-02-15 13:07 UTC, UlrichKu commented on Resources/views/webModules/MTPageMeta/standard.view.php
> +// TODO what about other MTPageMeta/standard.view.php ("non-theme")?
ok done (see there)

2019-02-19 08:55 UTC, umulmrum approved these changes

2019-02-19 09:17 UTC, merged

2019-02-19 09:17 UTC, umulmrum commented
Thanks @UlrichKu